name: CI

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        mariadb_tag: [
          latest
        ]
        wordpress_tag: [
          latest
        ]
        node_tag: [
          14
        ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Create .env file
      run: |
        cp .env.dist .env

    - name: Generate self-signed CA
      uses: kofemann/action-create-certificate@v0.0.4
      with:
        hostcert: 'server.crt'
        hostkey: 'server.key'
        cachain: 'ca-chain.pem'

    - name: Move certificates
      run: |
        mkdir -p tmp/certs
        mv server.crt server.key ca-chain.pem tmp/certs/
  
    - name: Run Makefile tasks
      run: |
        make test MARIADB_TAG=$MARIADB_TAG WORDPRESS_TAG=$WORDPRESS_TAG NODE_TAG=$NODE_TAG
        make down
