name: CI

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        mariadb_tag: [
          latest
        ]
        wordpress_tag: [
          latest
        ]
        node_tag: [
          14
        ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Create .env file
      run: |
        cp .env.dist .env

    - name: Run Makefile tasks
      run: |
        make test MODE=production MARIADB_TAG=$MARIADB_TAG WORDPRESS_TAG=$WORDPRESS_TAG NODE_TAG=$NODE_TAG
        make down
