name: CI

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        mariadb_tag: [
          latest
        ]
        wordpress_tag: [
          latest
        ]
        node_tag: [
          14
        ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Create .env file
      run: |
        cp .env.dist .env

    # method #1
    #- name: Install mkcert
    #  run: |
    #    sudo apt-get update && sudo apt-get install libnss3-tools
    #    wget -q -O - https://mkcert.dev/install.sh | sudo bash 

    # method #2
    - name: Generate self-signed CA
      uses: kofemann/action-create-certificate@v0.0.4
      with:
        hostcert: 'server.crt'
        hostkey: 'server.key'
        cachain: 'ca-chain.pem'

    - name: Move certificates
      run: |
        mkdir -p tmp/certs
        mv server.crt server.key ca-chain.pem tmp/certs/
  
    - name: Run Makefile tasks
      run: |
        make install \
          MARIADB_TAG=$MARIADB_TAG \
          WORDPRESS_TAG=$WORDPRESS_TAG \
          NODE_TAG=$NODE_TAG
        make test \
          MARIADB_TAG=$MARIADB_TAG \
          WORDPRESS_TAG=$WORDPRESS_TAG \
          NODE_TAG=$NODE_TAG
        make down
