name: CI

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        mariadb_tag: [
          latest
        ]
        wordpress_tag: [
          latest
        ]
        node_tag: [
          14
        ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Create .env file and certs directory
      run: |
        cp .env.dist .env
        mkdir certs

    - name: Generate self-signed CA
      uses: kofemann/action-create-certificate@v0.0.4
      with:
        hostcert: 'certs/server.crt'
        hostkey: 'certs/server.key'
        cachain: 'certs/ca-chain.pem'

    - name: Run Makefile tasks
      run: |
        make test MARIADB_TAG=$MARIADB_TAG WORDPRESS_TAG=$WORDPRESS_TAG NODE_TAG=$NODE_TAG
        make down
